### ISSUE TITLE
Training model with annos throws Xmin, Ymin,... error

### ISSUE THREAD

**Issue by robAndrus34** [weecology/DeepForest#992]
Hi, 

I'm running DeepForest in Google CoLab, and ran into an issue with the annotation file, I think.

To answer your User Story question, I'm a forest ecologist at Washington State University. I'm helping the City of Anacortes, WA to build a tree species map for ~3,000 acres of community owned forest land. The map will serve as the basis for a baseline assessment of forest health and a broader community led monitoring program.

Here's my issue. 

I'm trying to train the model. Attached are my annotations. Annotations were polygons. I converted them to annos using your tools. [WL_train_annotation.csv](https://github.com/user-attachments/files/19526200/WL_train_annotation.csv). I I can supply the image if needed, but I couldn't attach.

Here's my code to train the model

```
#initialize the model and change the corresponding config file
m = main.deepforest()
m.use_release()

#load the lastest release model
m.config["train"]["csv_file"] = '/content/drive/MyDrive/ACFL_Colab/Data/Imagery/model_training/WL_train_annotation.csv'
m.config["train"]["root_dir"] = '/content/drive/MyDrive/ACFL_Colab/Data/Imagery/model_training/'
m.config["score_thresh"] = 0.4
m.config["train"]['epochs'] = 2 #increase to 20 when no bugs
m.config["train"]["lr"] = 0.00001 #learning rates:currently low but vary this
m.config["train"]["fast_dev_run"] = True #for debugging

# Initialize the trainer
m.trainer.fit(m) #this line is throwing the error
```

**Here is the error that I'm getting**

KeyError: "None of [Index(['xmin', 'ymin', 'xmax', 'ymax'], dtype='object')] are in the [columns]"

I think this means that I need to have columns in my annotations file for xmin, ymin, etc... Do you agree or is there some other issue? 

Thank you!

**Comment by rhydham-nith** [comment]
Hello @robAndrus34 

please provide the images. i would like to try solving your issue.

**Comment by robAndrus34** [comment]
Hi @rhydham-nith, I sent you the file via email. Thank you

**Comment by rhydham-nith** [comment]
Hey @robAndrus34 ,

I was able to solve the error! 🎉

**What went wrong?**
DeepForest expects bounding box annotations (xmin, ymin, xmax, ymax), but the dataset had polygon coordinates instead, stored in a "geometry" column. Since the model couldn’t find the required columns, it threw a KeyError.

**How I fixed it:**

1. Extracted bounding boxes from the polygon coordinates using shapely.wkt.loads().
2. Created new columns: xmin, ymin, xmax, ymax.
3. Removed the geometry column and saved the fixed dataset.

Code for reference : 
``` 
pip install shapely

import pandas as pd
from shapely import wkt  # For parsing WKT strings

# Load your CSV
df = pd.read_csv("WL_train_annotation.csv")

# Function to extract bbox from POLYGON
def polygon_to_bbox(geom_str):
    polygon = wkt.loads(geom_str)  # Parse WKT string
    min_x, min_y, max_x, max_y = polygon.bounds  # Get bounding box
    return min_x, min_y, max_x, max_y

# Apply to each row
df[['xmin', 'ymin', 'xmax', 'ymax']] = df['geometry'].apply(
    lambda x: pd.Series(polygon_to_bbox(x))
)

# Drop the original geometry column (optional)
df = df.drop(columns=['geometry'])

# Save the new CSV
output_filename = "converted_annotations.csv"
df.to_csv(output_filename, index=False)

```

The converted anno file :  [converted_annotations.csv](https://github.com/user-attachments/files/19537051/converted_annotations.csv)


Let me know if I can help you with anything else!

**Comment by rhydham-nith** [comment]
Dear Mentors @ethanwhite @bw4sz @henrykironde ,

User @robAndrus34 encountered an issue while working with DeepForest’s training pipeline due to the format of the annotation file.

**Error Encountered:** ``` KeyError: "None of [Index(['xmin', 'ymin', 'xmax', 'ymax'], dtype='object')] are in the [columns]" ```

The error occurred because DeepForest requires bounding box annotations in the format (xmin, ymin, xmax, ymax), but the dataset had polygon coordinates stored in a "geometry" column instead.

### Possible Reasons for the Issue:

1. **Annotation File Creation Process**: The file may have been generated using tools or workflows that default to storing object annotations as polygons rather than bounding boxes.
2. **Format Expectation Misalignment**: The documentation may not explicitly mention the requirement to provide bounding box coordinates instead of polygon data.
3. **Dataset Source Variability**: Different annotation tools export datasets in various formats, and some may use polygons as the default representation.

### Potential Solutions:

1. Should we consider **updating the documentation** to clarify annotation format requirements for future users?
2. Would it be beneficial to **include a built-in function** in DeepForest to automatically convert polygon annotations to bounding boxes when needed?

Please let me know your thoughts on this. I’d be happy to contribute to any necessary improvements.

Best regards,
Rhydham Singla

**Comment by ethanwhite** [comment]
Thanks for reporting this @robAndrus34 and thanks to @rhydham-nith a temporary solution for Rob to work with! We do actually have a function (that is deprecated as part of the work mentioned below but is still present) that will do this conversion: [`shapefile_to_annotations`](https://deepforest.readthedocs.io/en/v1.5.0/source/deepforest.html#deepforest.utilities.shapefile_to_annotations).

We've been working on supporting different kinds of annotations so that we can work with points and polygons as well as bounding boxes. So, yes, in the case of bounding box based models (like the main retinanet model) we should support the automatic handling of the square polygon data read in by `read_file()`. @bw4sz has been doing this work and should be back around tomorrow and can let us know if this functionality still needs to be added or if it just isn't working quite right.

**Comment by robAndrus34** [comment]
@rhydham-nith, thanks to much for your help and solving my issue! 

@ethanwhite, I previously used the shapefile_to_annotations function. I'm not 100% certain about this, but I feel like it stopped working within the last few weeks, possibly as a result of the deprecation. Looking forward to hearing what @bw4sz has to say.

Cheers!

**Comment by bw4sz** [comment]
Okay, I am a bit late to the thread. @robAndrus34 I don't have the original data, can you just print the first row of it so I can see it, make a dummy dataset that shows a problem and I can inspect any errors.

**Comment by bw4sz** [comment]
> Dear Mentors [@ethanwhite](https://github.com/ethanwhite) [@bw4sz](https://github.com/bw4sz) [@henrykironde](https://github.com/henrykironde) ,
> 
> User [@robAndrus34](https://github.com/robAndrus34) encountered an issue while working with DeepForest’s training pipeline due to the format of the annotation file.
> 
> **Error Encountered:** `KeyError: "None of [Index(['xmin', 'ymin', 'xmax', 'ymax'], dtype='object')] are in the [columns]"`
> 
> The error occurred because DeepForest requires bounding box annotations in the format (xmin, ymin, xmax, ymax), but the dataset had polygon coordinates stored in a "geometry" column instead.
> 
> ### Possible Reasons for the Issue:
> 1. **Annotation File Creation Process**: The file may have been generated using tools or workflows that default to storing object annotations as polygons rather than bounding boxes.
> 2. **Format Expectation Misalignment**: The documentation may not explicitly mention the requirement to provide bounding box coordinates instead of polygon data.
> 3. **Dataset Source Variability**: Different annotation tools export datasets in various formats, and some may use polygons as the default representation.
> 
> ### Potential Solutions:
> 1. Should we consider **updating the documentation** to clarify annotation format requirements for future users?
> 2. Would it be beneficial to **include a built-in function** in DeepForest to automatically convert polygon annotations to bounding boxes when needed?
> 
> Please let me know your thoughts on this. I’d be happy to contribute to any necessary improvements.
> 
> Best regards, Rhydham Singla

These suggestions are not correct. DeepForest is moving towards polygon annotations and models. We could provide easy tools to switch from polygons to bounding boxes. That should not be the issue.

**Comment by robAndrus34** [comment]
Hi @bw4sz., I created bounding box (squares) annotations as an input to train the model (along with the image file). That may be a little outdated, but I'm guessing it'll still work. To convert the shapefile to annotations, I used shapefile_to_annotations. This is a screenshot of the output.

<img width="792" alt="Image" src="https://github.com/user-attachments/assets/206d2468-189d-41d3-a10a-e8a0b36d271b" />

I will share the coLab file with you and the data files via email. I feel like I should be able to do that via git, but I don't know how. 

Thank you, Robbie

**Comment by robAndrus34** [comment]
Hi @bw4sz, I just wanted to pass along that the suggestions of @rhydham-nith did fix the code issue and it no longer returns an error. It sounds like there are other issues at play here, so I'll leave that to you two.

**Comment by bw4sz** [comment]
Closing as user is satisfied and I will open any new issues that arise from testing this.

**Comment by bw4sz** [comment]
I could not find any error

```
from deepforest import main
from deepforest.utilities import read_file

df = read_file("/Users/benweinstein/Downloads/ACFL_andrus/WL_train_annotation.csv")
df.head()

>>> df.head()
  label                                           geometry                                         image_path
0  Tree  POLYGON ((2993.22 31.073, 2992.931 237.232, 28...  ACFL_Whistle_Lake_Training_Area_Pictometry_202...
1  Tree  POLYGON ((2681.958 7.165, 2827.88 8.318, 2825....  ACFL_Whistle_Lake_Training_Area_Pictometry_202...
2  Tree  POLYGON ((2899.005 379.073, 2809.616 379.281, ...  ACFL_Whistle_Lake_Training_Area_Pictometry_202...
3  Tree  POLYGON ((2706.172 457.495, 2707.142 364.762, ...  ACFL_Whistle_Lake_Training_Area_Pictometry_202...
4  Tree  POLYGON ((2759.549 193.576, 2886.879 194.176, ...  ACFL_Whistle_Lake_Training_Area_Pictometry_202...

```

**Comment by robAndrus34** [comment]
@bw4sz, the shape file is here -  

[ACFL_Training.zip](https://github.com/user-attachments/files/19557919/ACFL_Training.zip)

I would not expect to find the error with the code you wrote to load the file. However, when I use the annotation file in the code I pasted below, I got this error and the output referenced the issue coming from m.trainer.fit(m) -- 

KeyError: "None of [Index(['xmin', 'ymin', 'xmax', 'ymax'], dtype='object')] are in the [columns]"

As @rhydham-nith noted, the model appears to want a annotation file with Xmin, Ymin, etc.. 

Here is the code that threw the error. 

#initialize the model and change the corresponding config file
m = main.deepforest()
m.use_release()

#load the lastest release model
m.config["train"]["csv_file"] = '/content/drive/MyDrive/ACFL_Colab/Data/Imagery/model_training/WL_train_annotation.csv'
m.config["train"]["root_dir"] = '/content/drive/MyDrive/ACFL_Colab/Data/Imagery/model_training/'
m.config["score_thresh"] = 0.4
m.config["train"]['epochs'] = 2 #increase to 20 when no bugs
m.config["train"]["lr"] = 0.00001 #learning rates:currently low but vary this
m.config["train"]["fast_dev_run"] = True #for debugging

# Initialize the trainer
m.trainer.fit(m) #this line is throwing the error

**Comment by bw4sz** [comment]
Reopening, I understand the error now. Confirmed that I can reproduce.

```
from deepforest.utilities import read_file
from deepforest import main

df = read_file("/Users/benweinstein/Downloads/ACFL_andrus/WL_train_annotation.csv")
df.head()

#initialize the model and change the corresponding config file
m = main.deepforest()
m.use_release()

#load the lastest release model
m.config["train"]["csv_file"] = '/Users/benweinstein/Downloads/ACFL_andrus/WL_train_annotation.csv'
m.config["train"]["root_dir"] = '/Users/benweinstein/Downloads/ACFL_andrus/'
m.config["score_thresh"] = 0.4
m.config["train"]['epochs'] = 2 #increase to 20 when no bugs
m.config["train"]["lr"] = 0.00001 #learning rates:currently low but vary this
m.config["train"]["fast_dev_run"] = True #for debugging

m.create_trainer()
m.trainer.fit(m)
```

The dataset class is pulling from xmin, xmax, ymin, ymax, but the read_file only generates a 'geometry' column when read from shapefiles.

**Comment by robAndrus34** [comment]
@bw4sz, this all makes sense. The annotation file (.csv) that you looked at was produced from shapefile_to_annotation. It appears that this function is not working properly or am I missing something?

**Comment by bw4sz** [comment]
The function should not be used directly and was wrapped into read_file several versions ago, pushing a fix for the interaction of the behavior now. Thanks for reporting. We should inspect the docs and look for any examples of where we still call shapefile_to_annotation directly.
